# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:

  ca0.org2.example.com: 
    container_name: ca0.org2.blockchain.com
    image: hyperledger/fabric-ca:x86_64-1.1.0
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server 
      - FABRIC_CA_SERVER_CA_NAME=ca0.org2.blockchain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false 
    # docker启动后启动一个ca server ，注意修改根证书和admin密码
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.blockchain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/0eff510d29d2b234f54d06724c55be1b3c1565757466290d29e2f2e5980afc8a_sk -b admin:adminpw -d'
    volumes: 
      - ./crypto-config/peerOrganizations/org2.blockchain.com/ca/:/etc/hyperledger/fabric-ca-server-config 
    ports: 
      - "7054:7054" 