# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:

  ca0.org1.blockchain.com: 
    container_name: ca0.org1.blockchain.com
    image: hyperledger/fabric-ca:x86_64-1.1.0
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca0.org1.blockchain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false 
    # docker启动后启动一个ca server ，注意修改根证书和admin密码
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.blockchain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/91149c0b114d90734040d51964c6dae28bc3f85dedc5f11f44679b5fd66d40b4_sk -b admin:adminpw -d'
    volumes: 
      - ./crypto-config/peerOrganizations/org1.blockchain.com/ca/:/etc/hyperledger/fabric-ca-server-config 
    ports: 
      - "7054:7054" 
